abstract class AppStates {}
class AppIntialState extends AppStates{}
class AppChangeBottomNavigationBar extends AppStates{}
class AppCreatDataBaseState extends AppStates{}
class AppGetDataBaseState extends AppStates{}
class AppGetDataBaseLoadingState extends AppStates{}
class AppInsertDataBaseState extends AppStates{}
class AppChangeBottomSheetState extends AppStates{}
class AppUpdateDataBaseState extends AppStates{}
class AppDeletDataBaseState extends AppStates{}